/**
 * AfterCare Discharge AI - Mock Data Fixtures
 * Sample discharge summaries and data for testing and demonstration
 */

import type { DischargeSummary, GroceryItem } from './schemas.js';

/**
 * Sample discharge summary: Post-appendectomy patient with diabetes
 */
export const SAMPLE_DISCHARGE_APPENDECTOMY: DischargeSummary = {
  patient_name: 'John Smith',
  discharge_date: '2024-01-25',
  admission_reason: 'Acute appendicitis requiring emergency surgery',
  diagnoses: [
    'Acute appendicitis',
    'Type 2 diabetes mellitus',
    'Hypertension',
    'Hyperlipidemia',
  ],
  medications: [
    {
      name: 'Amoxicillin-clavulanate',
      dosage: '500mg',
      frequency: 'three times daily',
      route: 'oral',
      duration: '7 days',
      instructions: 'Take with food to reduce stomach upset',
      reason: 'Infection prevention post-surgery',
    },
    {
      name: 'Acetaminophen',
      dosage: '500mg',
      frequency: 'every 6 hours as needed',
      route: 'oral',
      duration: 'until pain resolves',
      instructions: 'Do not exceed 3000mg per day',
      reason: 'Pain management',
    },
    {
      name: 'Metformin',
      dosage: '1000mg',
      frequency: 'twice daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take with meals',
      reason: 'Diabetes management',
    },
    {
      name: 'Lisinopril',
      dosage: '10mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take in the morning',
      reason: 'Blood pressure control',
    },
    {
      name: 'Atorvastatin',
      dosage: '20mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take in the evening',
      reason: 'Cholesterol management',
    },
  ],
  dietary_restrictions: [
    {
      type: 'low-sodium',
      reason: 'Hypertension management',
      duration: 'ongoing',
    },
    {
      type: 'diabetic',
      reason: 'Blood sugar control',
      duration: 'ongoing',
    },
    {
      type: 'low-fat',
      reason: 'Post-surgery digestion',
      duration: '2 weeks',
    },
  ],
  activity_restrictions: [
    {
      restriction: 'No heavy lifting',
      weight_limit: '5 lbs',
      duration: '4 weeks',
      reason: 'Surgical incision healing',
    },
    {
      restriction: 'Limited walking',
      duration: '1 week',
      reason: 'Post-operative recovery',
    },
    {
      restriction: 'No driving',
      duration: '1 week',
      reason: 'Pain medication use and surgical recovery',
    },
  ],
  follow_ups: [
    {
      provider_type: 'Surgeon',
      provider_name: 'Dr. Sarah Johnson',
      specialty: 'General Surgery',
      timing: '1 week',
      reason: 'Incision check and suture removal',
      contact_info: '(555) 123-4567',
    },
    {
      provider_type: 'Primary Care',
      provider_name: 'Dr. Michael Chen',
      specialty: 'Internal Medicine',
      timing: '2 weeks',
      reason: 'Post-operative follow-up and medication review',
      contact_info: '(555) 234-5678',
    },
    {
      provider_type: 'Endocrinology',
      provider_name: 'Dr. Patricia Williams',
      specialty: 'Diabetes Management',
      timing: '4 weeks',
      reason: 'Diabetes management post-surgery',
      contact_info: '(555) 345-6789',
    },
  ],
  allergies: ['Penicillin (rash)', 'Sulfa drugs (rash)'],
  kidney_function: 'Normal (eGFR 85)',
  liver_function: 'Normal',
  other_conditions: ['Mild arthritis in knees'],
  missing_data_flags: [],
};

/**
 * Sample discharge summary: Post-cardiac event patient
 */
export const SAMPLE_DISCHARGE_CARDIAC: DischargeSummary = {
  patient_name: 'Margaret Davis',
  discharge_date: '2024-01-24',
  admission_reason: 'Acute myocardial infarction (heart attack) with stent placement',
  diagnoses: [
    'Acute myocardial infarction',
    'Coronary artery disease',
    'Hypertension',
    'Hyperlipidemia',
    'Atrial fibrillation',
  ],
  medications: [
    {
      name: 'Aspirin',
      dosage: '81mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take with food',
      reason: 'Blood clot prevention',
    },
    {
      name: 'Clopidogrel',
      dosage: '75mg',
      frequency: 'once daily',
      route: 'oral',
      duration: '12 months',
      instructions: 'Do not stop without consulting cardiologist',
      reason: 'Stent protection',
    },
    {
      name: 'Metoprolol',
      dosage: '50mg',
      frequency: 'twice daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take with meals',
      reason: 'Heart rate and blood pressure control',
    },
    {
      name: 'Lisinopril',
      dosage: '5mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take in the morning',
      reason: 'Blood pressure and heart protection',
    },
    {
      name: 'Atorvastatin',
      dosage: '80mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take in the evening',
      reason: 'Cholesterol management',
    },
    {
      name: 'Amiodarone',
      dosage: '200mg',
      frequency: 'once daily',
      route: 'oral',
      duration: 'ongoing',
      instructions: 'Take at same time each day',
      reason: 'Irregular heartbeat control',
    },
  ],
  dietary_restrictions: [
    {
      type: 'low-sodium',
      reason: 'Heart failure prevention',
      duration: 'ongoing',
    },
    {
      type: 'low-fat',
      reason: 'Cholesterol management',
      duration: 'ongoing',
    },
    {
      type: 'fluid-restricted',
      reason: 'Heart function support',
      duration: 'ongoing',
    },
  ],
  activity_restrictions: [
    {
      restriction: 'Cardiac rehabilitation program',
      duration: '8 weeks',
      reason: 'Supervised exercise recovery',
    },
    {
      restriction: 'No strenuous activity',
      duration: '6 weeks',
      reason: 'Heart healing',
    },
    {
      restriction: 'Gradual return to normal activities',
      duration: '3 months',
      reason: 'Progressive cardiac recovery',
    },
  ],
  follow_ups: [
    {
      provider_type: 'Cardiologist',
      provider_name: 'Dr. Robert Thompson',
      specialty: 'Cardiology',
      timing: '1 week',
      reason: 'Post-stent evaluation',
      contact_info: '(555) 456-7890',
    },
    {
      provider_type: 'Cardiac Rehabilitation',
      timing: 'Start within 1 week',
      reason: 'Supervised exercise program',
      contact_info: '(555) 567-8901',
    },
    {
      provider_type: 'Primary Care',
      timing: '2 weeks',
      reason: 'General post-operative follow-up',
      contact_info: '(555) 678-9012',
    },
  ],
  allergies: ['Latex', 'Iodine (contrast dye reaction)'],
  kidney_function: 'Mild reduction (eGFR 55)',
  liver_function: 'Normal',
  other_conditions: ['Sleep apnea', 'Obesity'],
  missing_data_flags: [],
};

/**
 * Sample grocery items for post-surgery recovery
 */
export const SAMPLE_GROCERY_ITEMS: GroceryItem[] = [
  {
    name: 'Chicken breast',
    category: 'protein',
    quantity: '2 lbs',
    unit_price: 8.99,
    reason: 'Lean protein for wound healing',
    preparation_notes: 'Bake or poach; avoid frying',
    safe_for_restrictions: true,
  },
  {
    name: 'Salmon fillet',
    category: 'protein',
    quantity: '1.5 lbs',
    unit_price: 12.99,
    reason: 'Omega-3 fatty acids for inflammation reduction',
    preparation_notes: 'Bake at 375°F for 15 minutes',
    safe_for_restrictions: true,
  },
  {
    name: 'Greek yogurt',
    category: 'dairy',
    quantity: '32 oz',
    unit_price: 5.99,
    reason: 'Protein and probiotics for gut health',
    preparation_notes: 'Plain, unsweetened variety',
    safe_for_restrictions: true,
  },
  {
    name: 'Eggs',
    category: 'protein',
    quantity: '1 dozen',
    unit_price: 3.49,
    reason: 'Complete protein and choline for healing',
    preparation_notes: 'Soft-boiled or scrambled',
    safe_for_restrictions: true,
  },
  {
    name: 'Broccoli',
    category: 'vegetable',
    quantity: '2 lbs',
    unit_price: 3.99,
    reason: 'Vitamin C and fiber for healing',
    preparation_notes: 'Steam until soft; avoid raw',
    safe_for_restrictions: true,
  },
  {
    name: 'Carrots',
    category: 'vegetable',
    quantity: '2 lbs',
    unit_price: 2.49,
    reason: 'Beta-carotene for immune function',
    preparation_notes: 'Cook until tender',
    safe_for_restrictions: true,
  },
  {
    name: 'Sweet potato',
    category: 'vegetable',
    quantity: '3 lbs',
    unit_price: 4.99,
    reason: 'Complex carbs and vitamin A',
    preparation_notes: 'Bake or steam',
    safe_for_restrictions: true,
  },
  {
    name: 'Brown rice',
    category: 'grain',
    quantity: '2 lbs',
    unit_price: 3.99,
    reason: 'Whole grain for sustained energy',
    preparation_notes: 'Cook 45 minutes; serve soft',
    safe_for_restrictions: true,
  },
  {
    name: 'Oatmeal',
    category: 'grain',
    quantity: '32 oz',
    unit_price: 4.49,
    reason: 'Soluble fiber and sustained energy',
    preparation_notes: 'Cook with low-sodium broth',
    safe_for_restrictions: true,
  },
  {
    name: 'Bananas',
    category: 'fruit',
    quantity: '2 lbs',
    unit_price: 1.99,
    reason: 'Potassium and easy-to-digest carbs',
    preparation_notes: 'Soft and easy to eat',
    safe_for_restrictions: true,
  },
  {
    name: 'Blueberries',
    category: 'fruit',
    quantity: '1 lb',
    unit_price: 5.99,
    reason: 'Antioxidants for healing',
    preparation_notes: 'Fresh or frozen',
    safe_for_restrictions: true,
  },
  {
    name: 'Apples',
    category: 'fruit',
    quantity: '3 lbs',
    unit_price: 3.99,
    reason: 'Fiber and vitamin C',
    preparation_notes: 'Peel and cook until soft',
    safe_for_restrictions: true,
  },
  {
    name: 'Low-sodium chicken broth',
    category: 'liquid',
    quantity: '32 oz',
    unit_price: 2.99,
    reason: 'Hydration and minerals',
    preparation_notes: 'Use for soups and cooking',
    safe_for_restrictions: true,
  },
  {
    name: 'Honey',
    category: 'condiment',
    quantity: '12 oz',
    unit_price: 6.99,
    reason: 'Natural energy and throat soothing',
    preparation_notes: 'Add to tea or oatmeal',
    safe_for_restrictions: true,
  },
  {
    name: 'Olive oil',
    category: 'oil',
    quantity: '25.5 oz',
    unit_price: 8.99,
    reason: 'Healthy fat for nutrient absorption',
    preparation_notes: 'Use for light cooking',
    safe_for_restrictions: true,
  },
  {
    name: 'Ginger',
    category: 'spice',
    quantity: '4 oz',
    unit_price: 2.99,
    reason: 'Anti-inflammatory and nausea relief',
    preparation_notes: 'Fresh; steep in hot water',
    safe_for_restrictions: true,
  },
  {
    name: 'Turmeric',
    category: 'spice',
    quantity: '2 oz',
    unit_price: 3.99,
    reason: 'Anti-inflammatory properties',
    preparation_notes: 'Add to soups and rice',
    safe_for_restrictions: true,
  },
  {
    name: 'Garlic',
    category: 'vegetable',
    quantity: '1 bulb',
    unit_price: 0.99,
    reason: 'Immune support and flavor',
    preparation_notes: 'Mince and cook in broth',
    safe_for_restrictions: true,
  },
  {
    name: 'Almonds',
    category: 'nut',
    quantity: '8 oz',
    unit_price: 7.99,
    reason: 'Protein and healthy fat',
    preparation_notes: 'Soak in water to soften',
    safe_for_restrictions: true,
  },
  {
    name: 'Herbal tea',
    category: 'beverage',
    quantity: '20 bags',
    unit_price: 3.99,
    reason: 'Hydration and soothing',
    preparation_notes: 'Chamomile or ginger varieties',
    safe_for_restrictions: true,
  },
];
